AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - test/dummy/**/*
    - vendor/**/*

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - test/dummy/bin/*
