fix: true
format: progress
ruby_version: 2.5

ignore:
  - 'db/schema.rb'
  - 'vendor/**/*'
  - 'test/dummy/bin/*':
    - Style/MixinUsage
  - 'test/integration/navigation_test.rb':
    - Naming/AccessorMethodName
